services:
  - type: web
    name: stannet-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: OWNER_NUMBER
        value: "2348164103797"
      - key: OMADA_URL
        value: "https://192.168.1.42:8043"
      - key: OMADA_USERNAME
        value: "stannet"
      - key: OMADA_PASSWORD
        sync: false
    plan: free